apiVersion: v1
kind: ReplicationController
metadata:
  name: minecraft-api-v3
  # The labels will be applied automatically
  # from the labels in the pod template, if not set
spec:
  replicas: 1
  # The selector will be applied automatically
  # from the labels in the pod template, if not set.
  selector:
    app: minecraft-api-v3
  template:
    metadata:
      labels:
        app: minecraft-api-v3
    spec:
      containers:
      - name: minecraft-api-v3
        image: containersopenhackteam10.azurecr.io/minecraft-api:v1
        ports:
          - containerPort: 80
            name: api-port
      imagePullSecrets:
      - name: acr-auth
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: minecraft-api-v3
  name: minecraft-api-v3
spec:
  ports:
  - name: api-port
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: minecraft-api-v3
  type: LoadBalancer